In [ ]:
'''Q1. What is the difference between Ordinal Encoding and Label Encoding? Provide an example of when you
might choose one over the other.
Answer-Ordinal encoding and label encoding are two techniques used for encoding categorical data.

Ordinal encoding is a technique that assigns a unique integer value to each category in a feature based on the order
or rank of the category. For example, in a feature with categories "low", "medium", and "high", we can assign integer 
values 1, 2, and 3 respectively. Ordinal encoding preserves the order of the categories, but does not necessarily provide
any meaningful relationship between the assigned values.

Label encoding, on the other hand, assigns a unique integer value to each category in a feature without any regard to the
order or rank of the category. For example, in a feature with categories "red", "green", and "blue", we can assign integer
values 1, 2, and 3 respectively. Label encoding does not preserve the order of the categories.

When our categorical data is follow the rank or order of the values then it is useful to use the ordinal Encoding over Lablel
Encoding but if our categorical data is not follows the order or ranking then it is useful to use Label Encoding in place of 
Ordinal Encoding.'''

In [ ]:
'''Q2. Explain how Target Guided Ordinal Encoding works and provide an example of when you might use it in
a machine learning project.
Answer-Target Guided Ordinal Encoding is a technique used to encode categorical variables in a way that is based on the 
relationship between the variable and the target variable. This technique can be particularly useful when the categorical 
variable has a high number of categories, and when we want to incorporate information about the target variable into the 
encoding process.

The basic idea behind Target Guided Ordinal Encoding is to rank the categories of the categorical variable based on the 
target variable, and then replace the categories with the corresponding rank. This can be done by calculating the mean or 
median of the target variable for each category and then ranking the categories based on their mean or median value. The 
lowest ranked category is then replaced with the value 1, the second lowest with the value 2, and so on.

Here is an example of how Target Guided Ordinal Encoding works in practice. Let's say we have a categorical variable "city"
with four categories: New York, San Francisco, Boston, and Chicago. We also have a target variable "salary", which represents
the annual salary of individuals living in each city. We want to encode the "city" variable in a way that takes into account 
the relationship between the city and the salary.

We can use Target Guided Ordinal Encoding to rank the cities based on their mean salary. The mean salary for each city is as 
follows:

New York: $100,000
San Francisco: $120,000
Boston: $90,000
Chicago: $80,000
Based on these values, we can assign the rank 1 to San Francisco (the city with the highest mean salary), rank 2 to New York,
rank 3 to Boston, and rank 4 to Chicago. We can then replace the original categories with their corresponding ranks.

Target Guided Ordinal Encoding can be useful in a machine learning project when we want to incorporate information about the 
target variable into the encoding process, especially when dealing with categorical variables with a high number of categories.''' This technique can help improve the predictive power of the model by encoding the variable in a way that takes into account the relationship between the variable and the target.





In [ ]:
'''Q3. Define covariance and explain why it is important in statistical analysis. How is covariance calculated?
Answer-Covariance is a statistical measure that describes how two variables change in relation to each other. More 
specifically, it measures the degree to which two variables are linearly associated with each other. When two variables
have a positive covariance, they tend to increase or decrease together, while two variables with a negative covariance tend 
to have an inverse relationship where one variable increases as the other decreases.

Covariance is important in statistical analysis because it helps to identify the degree and direction of the relationship 
between two variables. It is commonly used in fields such as finance, economics, and social sciences to study the relationship
between different variables, such as the relationship between stock prices and interest rates or the relationship between 
education level and income.

The formula for calculating covariance between two variables X and Y can be expressed as:

cov(X, Y) = Σ [(Xi - X̄)(Yi - Ȳ)] / (n - 1)

where Xi and Yi are the individual values of X and Y, X̄ and Ȳ are the means of X and Y respectively, and n is the number of 
observations.

The resulting covariance value can be positive, negative, or zero. A positive covariance indicates a direct relationship 
between the variables, meaning that as one variable increases, the other variable also tends to increase. A negative 
covariance indicates an inverse relationship, meaning that as one variable increases, the other variable tends to decrease.
A covariance of zero indicates no relationship between the variables.

However, covariance alone does not provide a complete picture of the relationship between two variables as it is affected by
the scale of the variables. Therefore, it is often normalized by dividing it by the product of the standard deviations of the
two variables to obtain the correlation coefficient. The resulting correlation coefficient has a value between -1 and 1, where
a value of 1 indicates a perfect positive correlation, a value of -1 indicates a perfect negative correlation, and a value of
0 indicates no correlation.'''

In [1]:
'''Q4. For a dataset with the following categorical variables: Color (red, green, blue), Size (small, medium,
large), and Material (wood, metal, plastic), perform label encoding using Python's scikit-learn library.
Show your code and explain the output.'''
from sklearn.preprocessing import LabelEncoder
import pandas as pd

# Create a sample dataset
data = {'Color': ['red', 'green', 'blue', 'blue', 'red', 'green', 'blue'],
        'Size': ['small', 'large', 'medium', 'small', 'medium', 'large', 'medium'],
        'Material': ['wood', 'metal', 'plastic', 'plastic', 'metal', 'wood', 'plastic']}

df = pd.DataFrame(data)

# Initialize LabelEncoder
le = LabelEncoder()

# Label encode categorical variables
df['Color'] = le.fit_transform(df['Color'])
df['Size'] = le.fit_transform(df['Size'])
df['Material'] = le.fit_transform(df['Material'])

print(df)


   Color  Size  Material
0      2     2         2
1      1     0         0
2      0     1         1
3      0     2         1
4      2     1         0
5      1     0         2
6      0     1         1


In [2]:
'''Q5. Calculate the covariance matrix for the following variables in a dataset: Age, Income, and Education
level. Interpret the results.'''
import numpy as np

# Create a sample dataset with Age, Income, and Education level
age = [25, 30, 35, 40, 45]
income = [50000, 60000, 70000, 80000, 90000]
education_level = [12, 14, 16, 18, 20]

# Calculate covariance matrix
cov_matrix = np.cov([age, income, education_level])

print("Covariance Matrix:\n", cov_matrix)


Covariance Matrix:
 [[6.25e+01 1.25e+05 2.50e+01]
 [1.25e+05 2.50e+08 5.00e+04]
 [2.50e+01 5.00e+04 1.00e+01]]


In [ ]:
'''Q6. You are working on a machine learning project with a dataset containing several categorical
variables, including "Gender" (Male/Female), "Education Level" (High School/Bachelor's/Master's/PhD),
and "Employment Status" (Unemployed/Part-Time/Full-Time). Which encoding method would you use for
each variable, and why?
Answer-For the categorical variable Gender we use Label Encoding because this variable does not havve any rank.
For variable eduaction Level we use Ordinal Encoding because we can find that there is an order of these values
like for the lower education we can give low value and for the Higher Education we can assign  high value.
For the Employement Status we can use One Hot  Encoding because this variable does not have any rank or order.'''

In [3]:
'''Q7. You are analyzing a dataset with two continuous variables, "Temperature" and "Humidity", and two
categorical variables, "Weather Condition" (Sunny/Cloudy/Rainy) and "Wind Direction" (North/South/
East/West). Calculate the covariance between each pair of variables and interpret the results.'''
import numpy as np

# Example dataset
temperature = [25, 28, 30, 32, 27]
humidity = [50, 60, 65, 70, 55]
weather_condition = ['Sunny', 'Cloudy', 'Rainy', 'Cloudy', 'Sunny']
wind_direction = ['North', 'South', 'East', 'West', 'South']

# Convert categorical variables to numerical using Label Encoding
from sklearn.preprocessing import LabelEncoder
weather_le = LabelEncoder()
wind_le = LabelEncoder()
weather_encoded = weather_le.fit_transform(weather_condition)
wind_encoded = wind_le.fit_transform(wind_direction)

# Calculate the covariance matrix
data = np.array([temperature, humidity, weather_encoded, wind_encoded])
covariance_matrix = np.cov(data)

# Print the covariance matrix
print("Covariance Matrix:\n", covariance_matrix)


Covariance Matrix:
 [[ 7.3  21.25 -2.    0.95]
 [21.25 62.5  -6.25  2.5 ]
 [-2.   -6.25  1.   -0.5 ]
 [ 0.95  2.5  -0.5   1.3 ]]
